services:
  goapp:
    image: golang:1.23
    entrypoint: sh -c "tail -f /dev/null"
    container_name: go-otel
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app